local cfg = {}

cfg.items = {
  ["masterpick"] = { "Master Pick",1.0},
  ["lockpick"] = { "Lock Pick",1.0},
  ["pacote_ilegal"] = { "Pacote",5.0},
  ["garrafavazia"] = { "Garrafa Vazia",1.0},
  ["garrafadeleite"] = { "Garrafa de Leite",1.0},
  ["bank_money"] = { "Dinheiro do Banco",0},
  ["benzoilmetilecgonina"] = { "Semente de Cocaina",1.0},
  ["anfetamina"] = { "Semente de MD",1.0},
  ["md"] = { "MD",1.0},
  ["seeds"] = { "Semente de Maconha",1.0},
  ["weed"] = { "Maconha",1.0},
  ["furadeira"] = { "Furadeira",2.0},
  ["solda"] = { "Solda",2.0},
  ["isca"] = { "Isca",0.6 },
	["dourado"] = { "Dourado",0.6 },
	["corvina"] = { "Corvina",0.6 },
	["salmao"] = { "Salmão",0.6 },
  ["pacu"] = { "Pacu",0.6 },
  ["radio"] = { "Radio",0.2 },
	["pintado"] = { "Pintado",0.6 },
	["pirarucu"] = { "Pirarucu",0.6 },
	["tilapia"] = { "Tilápia",0.6 },
	["tucunare"] = { "Tucunaré",0.6 },
	["lambari"] = { "Lambari",0.6 },
  ["cocaine"] = { "Cocaina",1.0},
  ["mochila1"] = { "Mochila Pequena", 3.0},
  ["mochila2"] = { "Mochila Media", 6.0},
  ["mochila3"] = { "Mochila Grande", 8.0},
  ["oab_identidade"] = { "OAB Identidade",0},
  ["nitro"] = { "Nitro",10.0},
  ["roupas2"] = { "Roupas",1.0},
  ["oculos"] = { "Óculos",0.5},
  ["sapatos"] = { "Sapatos",0.5},
  ["chapeu"] = { "Chapeu",0.5},
  ["body_armor"] = { "Colete",5.0},
  ["night_vison"] = { "Visao noturna",5.0},
  ["alianca"] = { "Alianca de Casamento",1.0},
  ["certificado"] = {"Teste Psicológico", 1.0},
  ["documento"] = {"Aprovação Judicial", 1.0},
  ["escudo"] = {"Escudo Balistico", 20.0 },
  ["medal1"] = {"Broche de Ouro", 0},
  ["medal2"] = {"Broche de Prata", 0},
  ["medal3"] = {"Broche de Bronze", 0},
  ["medkit"] = { "Kit Médico",   0.1},
  ["repairkit"] = { "Kit Reparador",  0.5},
  ["cartaovirgem"] = { "Cartão Crédito Virgem",1.0},
  ["cartaoclonado"] = { "Cartão Crédito Clonado",1.0},
  ["tartaruga"] = { "Tartaruga",5.0},
  ["carnetartaruga"] = { "Carne de Tartaruga",2.5},
  ["dirty_money"] = { "Dinheiro",  0},
  ["vendaolhos"] = { "Capuz",  0.1},
  ["algemas"] = { "Algemas",  0.5},
  ["chave_algemas"] = { "Chave de Algemas",  0.3},
  ["scubagear"] = { "Traje de Mergulho",  15},
  ["rocha"] = { "Rocha",2.0},
  ["ouro"] = { "Ouro",1.0},
  ["ferro"] = { "Ferro",1.0},
  ["bronze"] = { "Bronze",1.0},
  ["diamantelap"] = { "Diamante Lapidado",1.0},
  ["mandado_b_a"] = { "Mandado busca e apreensão",0.1},
  ["mandado_prisao"] = { "Mandado de prisão",0.1},
  ["mandado_intimacao"] = { "Mandado de intimação",0.1},
  ["processosjudiciais"] = { "Processos Judiciais",2.0},
  -----------------------
  -- COMPONENTES 
  -----------------------
  ["pack_parts"] = { "Pacote de Componentes",10.0},
  ["pistol_parts"] = { "Componente de Five-Seven",1.0},
  ["shotgun_parts"] = { "Componente da Shotgun",3.0},
  ["mtar_parts"] = { "Componente da MTAR-21",2.0},
  ["adv_parts"] = { "Componentes de Fuzil Avançado", 2.0},
  ["sns_parts"] = { "Componentes da HK310M", 2.0},
  ["ak47_parts"] = { "Componente da AK47",3.0},
  ["body_parts"] = { "Componente de Colete",1.0},
  ------------------------
  ["dipiroca"] = { "Dipirona",0.00},
  ["nocucedin"] = { "Morfina",0.00},
  ["paracetanal"] = { "Paracetamol",0.00},
  ["decupramim"] = { "Dorflex",0.00},
  ["buscopau"] = { "Buscopam",0.00},
  ["navagina"] = { "Novalgina",0.00},
  ["analdor"] = { "Anador",0.00},
  ["sefodex"] = { "Sustagem",0.00},
  ["phodac"] = { "Priozelam",0.00},
  ["danec"] = { "Danazol",0.00},
  ["cotovelol"] = { "Ciclo 21",0.00},
  ["nokusin"] = { "Rivotril",0.00},
  ["viagral"] = { "Viagra",0.00},
  ["glicoanal"] = { "Glicose",0.00},
  ["quigosado"] = { "PuranT4",0.00},
  ["bread"] = { "Pão",  0.5},
  ["donut"] = { "Donut",  0.2},
  ["tacos"] = { "Tacos",  0.2},
  ["sandwich"] = { "Sanduiche",  0.5},
  ["kebab"] = { "Kebab",  0.85},
  ["pdonut"] = { "Premium Donut",  0.5},
  ["catfish"] = { "Catfish",  0.3},
  ["lasanha"] = { "Lasanha",  1.0},
  ["vitamina"] = { "Vitamina",  1.0},
  ["water"] = { "Garrafa de Agua",  0.5},
  ["milk"] = { "Leite",  0.5},
  ["coffee"] = { "Café",  0.2},
  ["tea"] = { "Chá",  0.2},
  ["icetea"] = { "Chá-Gelado",  0.5},
  ["orangejuice"] = { "Suco de Laranja",  0.5},
  ["gocagola"] = { "Coca-Cola",  0.3},
  ["redgull"] = { "Red Bull",  0.3},
  ["lemonlimonad"] = { "Limonada",  0.3},
  ["vodka"] = { "Tequila",  0.5},
  ["madeira"] = { "Madeira",  3.0},
  ["tora"] = { "Tora",  9.0},
  ["nitro"] = { "Nitro",  3.0},
  ["rgfalso"] = { "RG", 5.0 },
  ["cadaver"] = {"Cadaver", 15.0 },
  ["parafuso"] = {"Parafuso", 0.5 },
  ["metal"] = {"Metal", 1.0 },
  ["bateria"] = {"Bateria", 2.0},
  ["cabo"] = {"Cabo para punhal", 0.5},
  ["orgaos"] = {"Orgãos", 5.0 },
  ["mascara"] = {"Mascara", 1.0 },
  ["celular"] = {"Celular", 0.8 },
  ["carnedetartaruga"] = {"Carne de Tartaruga", 3.0 },
  ["tartaruga"] = {"Tartaruga", 10.0 },
  ["barra"] = {"Barra de Ouro", 1.5 },
  ["brincos"] = {"Brincos", 0.5 },
  ["colar"] = {"Colar", 0.7 },
  ["relogio"] = {"Relógio Rolex", 1.0},
  ["joia"] = {"Diamante Raro", 1.5 },
  ["esmeralda"] = {"Esmeralda", 2.0 },
  ["ticket_race"] = {"Ticket", 1.0},

}

local function load_item_pack(name)
	local items = module("cfg/item/"..name)
	if items then
		for k,v in pairs(items) do
			cfg.items[k] = v
		end
	end
end

load_item_pack("armamentos")

return cfg